#!/bin/sh

# Option Texts
logout="logout"
reboot="reboot"
shutdown="shutdown"

# Options passed to Rofi
options="$logout\n$reboot\n$shutdown"

# Show dialog and store chosen option
chosen="$(echo "$options" | rofi -dmenu -p 'Select an option' -matching fuzzy)"

# Perform action based on choice
case $chosen in
	$logout)
		bspc quit
		;;
	$reboot)
		reboot
		;;
	$shutdown)
		shutdown now
		;;
esac
