#!/bin/sh

audio="audio"
graphics="graphics"
network="network"

chosen="$(echo "$audio\n$graphics\n$network" | rofi -dmenu -p "System Settings" -matching fuzzy)"

# Run settings menu based on choice
case $chosen in
	$audio)
		audiomenu
		;;
	$graphics)
		graphicsmenu
		;;
	$network)
		networkmenu
		;;
esac
