#! /bin/sh

# Create 10 workspaces
bspc monitor -d 一 二 三 四 五 六

# Configure BSPWM options
bspc config focused_border_color #e65a77
bspc config border_width         2
bspc config window_gap           16
bspc config top_padding          24
bspc config bottom_padding       28
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set BSPWM rules for specific programs
bspc rule -a Screenkey manage=off
bspc rule -a gsimplecal state=floating
bspc rule -a WPG state=floating
bspc rule -a *:Godot_Engine state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Steam state=floating
bspc rule -a yoinkscreen state=floating

# Set default cursor to pointer
xsetroot -cursor_name left_ptr &

# Play rain sound in background
rainyd &

# Start hotkey daemon
sxhkd &

# Generate color scheme, set wallpaper
$HOME/.config/wpg/wp_init.sh

# Generate lockscreen cache
betterlockscreen -u $HOME/.config/wallpapers/current &

# Launch polybar
polybar-launch &

# Launch plank dock
plank &
