#! /bin/sh

# Create 10 workspaces
bspc monitor -d 一 二 三 四 五 六 七 八 九 零

# Configure BSPWM options
bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set BSPWM rules for specific programs
bspc rule -a Screenkey manage=off
bspc rule -a gsimplecal state=floating
bspc rule -a WPG state=floating
bspc rule -a discord desktop="^3"
bspc rule -a slack desktop="^3"

# Set default cursor to pointer
xsetroot -cursor_name left_ptr &

# Play rain sound in background
rainyd &

# Start hotkey daemon
sxhkd &

# Generate color scheme, set wallpaper
$HOME/.config/wpg/wp_init.sh

# Generate lockscreen cache
betterlockscreen -u $HOME/.config/wallpapers/current &

# Launch polybar
$HOME/.config/polybar/launch.sh &

# Startup programs
discord &
slack &
